blank_issues_enabled: false
contact_links:
  - name: TrueNAS Help
    url: https://forums.truenas.com/
    about: Issues installing/configuring Fireshare on TrueNAS must be posted to a TrueNAS forum FIRST. TrueNAS issues opened here without a forum link will be closed and you will be banned.
