"""add image tables

Revision ID: 5a12c7f85737
Revises: k6f7g8h9i0j1
Create Date: 2026-04-09 19:41:07.456145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a12c7f85737'
down_revision = 'k6f7g8h9i0j1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('extension', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_folder', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_path'), ['path'], unique=False)

    op.create_table('image_game_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_metadata.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.image_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'game_id')
    )
    op.create_table('image_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('has_webp', sa.Boolean(), nullable=True),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.image_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_info_title'), ['title'], unique=False)

    op.create_table('image_tag_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.image_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['custom_tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'tag_id')
    )
    op.create_table('image_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.image_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'ip_address')
    )
    with op.batch_alter_table('video_info', schema=None) as batch_op:
        batch_op.alter_column('has_480p',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_720p',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_1080p',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_info', schema=None) as batch_op:
        batch_op.alter_column('has_1080p',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_720p',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_480p',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    op.drop_table('image_view')
    op.drop_table('image_tag_link')
    with op.batch_alter_table('image_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_info_title'))

    op.drop_table('image_info')
    op.drop_table('image_game_link')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_path'))
        batch_op.drop_index(batch_op.f('ix_image_image_id'))

    op.drop_table('image')
    # ### end Alembic commands ###
