"""add transcoding support

Revision ID: b7e8541487dc
Revises: a4503f708aee
Create Date: 2024-11-21 05:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e8541487dc'
down_revision = 'a4503f708aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_info', sa.Column('has_720p', sa.Boolean(), nullable=True))
    op.add_column('video_info', sa.Column('has_1080p', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows using SQLAlchemy's false() for cross-database compatibility
    from sqlalchemy import false
    op.execute('UPDATE video_info SET has_720p = 0 WHERE has_720p IS NULL')
    op.execute('UPDATE video_info SET has_1080p = 0 WHERE has_1080p IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_info', 'has_1080p')
    op.drop_column('video_info', 'has_720p')
    # ### end Alembic commands ###
