"""add transcoding support

Revision ID: b7e8541487dc
Revises: 4395905f3725
Create Date: 2024-11-21 05:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e8541487dc'
down_revision = '4395905f3725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default value of False for SQLite compatibility
    op.add_column('video_info', sa.Column('has_720p', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('video_info', sa.Column('has_1080p', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_info', 'has_1080p')
    op.drop_column('video_info', 'has_720p')
    # ### end Alembic commands ###
