"""empty message

Revision ID: d5598643eeee
Revises: 15c3881d9904
Create Date: 2022-06-04 23:55:09.868847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5598643eeee'
down_revision = '15c3881d9904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available')
    # ### end Alembic commands ###
